### PR TITLE
Sanitize Property Names

### PR DESCRIPTION
**Pull request by Tyler-IN**
See https://github.com/HavenDV/OpenApiGenerator/issues/14

This implements the proposal outlined in the issue.

### CODE REVIEW

**Comment by Tyler-IN** [comment]
Working through test cases, adding one for an unofficial generated Twitch OpenAPI document.

```cs
        public const string Primary(default) = "primary (default)";
```

Has additional scenarios such as the above.

**Comment by Tyler-IN** [comment]
image

Property name is still not sanitized here.

**Comment by Tyler-IN** [comment]
image

**Comment by HavenDV** [comment]
UseWordSeparator would turn this into PrimaryDefault. Will it be better?

**Comment by Tyler-IN** [comment]
I'll extend the init helper to do what FromSchema does

**Comment by Tyler-IN** [comment]
image

**Comment by Tyler-IN** [comment]
Now to see what's causing the CI failures...

**Comment by Tyler-IN** [comment]
Difference in output in `OpenApiGenerator.UnitTests.ClientTests.OpenAi`;
image

How do you want to address this @HavenDV ?

**Comment by HavenDV** [comment]
> Difference in output in `OpenApiGenerator.UnitTests.ClientTests.OpenAi`; image
> 
> How do you want to address this @HavenDV ? Note the enums below too.

It seems there is some kind of error with the OpenAI spec, and these models are skipped in the generation. I'll deal with this separately

**Comment by Tyler-IN** [comment]
Ok, with these changes CI should pass.

**Comment by Tyler-IN** [comment]
For note, the twitch integration tests are just placeholder filler.

**Comment by HavenDV** [comment]
The main place for testing in this project is the Snapshots tests, which compare the generated code and make sure that it does not produce any diagnostics (that is, it can compile). The tests here also allow you to debug the entire code, unlike integration tests, which use the generator itself without Roslyn

**Comment by HavenDV** [comment]
I will add twitch openapi spec to Snapshots tests little later today, I am at work now

**Pull request merged**
